import { NextResponse } from 'next/server';
import { kwhToCo2Kg } from '@/lib/energyCalculations';

/**
 * CarbonX — Export API (Task 9)
 * GET /api/export?type=csv   → AI-ready telemetry CSV dataset
 * GET /api/export?type=pdf   → Machine Health Report (PDF stub)
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const type = searchParams.get('type');

  if (type === 'csv') {
    // Generate AI-ready CSV with CarbonX energy telemetry
    const now = new Date();
    const rows: string[] = [
      'Timestamp,GatewayID,NodeID,NodeName,kWh,kVARh,CurrentKW,PowerFactor,Voltage_L1,Voltage_L2,Voltage_L3,Temp_C,CO2_kg,EnergyLoss_pct,HealthScore,Status',
    ];

    // Mock data rows (24h of readings)
    const nodes = [
      { nodeId: 'TX-1', name: 'CNC Machine A', kwh: 600.2, kvarh: 182, kw: 12.4, pf: 0.95, v: [399, 401, 400], temp: 62, health: 95, status: 'Healthy' },
      { nodeId: 'TX-2', name: 'Lathe B', kwh: 480.1, kvarh: 143, kw: 8.2, pf: 0.93, v: [398, 402, 400], temp: 55, health: 88, status: 'Healthy' },
      { nodeId: 'TX-3', name: 'Compressor Array', kwh: 820.5, kvarh: 312, kw: 45.1, pf: 0.82, v: [395, 405, 401], temp: 88, health: 62, status: 'Warning' },
      { nodeId: 'TX-4', name: 'HVAC System', kwh: 420.3, kvarh: 202, kw: 64.8, pf: 0.78, v: [390, 398, 395], temp: 95, health: 35, status: 'Critical' },
    ];

    for (const node of nodes) {
      const co2 = kwhToCo2Kg(node.kwh);
      rows.push(
        `${now.toISOString()},RX-PLANT-01,${node.nodeId},${node.name},` +
        `${node.kwh},${node.kvarh},${node.kw},${node.pf},` +
        `${node.v[0]},${node.v[1]},${node.v[2]},${node.temp},` +
        `${co2},1.8,${node.health},${node.status}`
      );
    }

    const csvContent = rows.join('\n');
    return new NextResponse(csvContent, {
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="CarbonX_AI_Dataset_${now.toISOString().split('T')[0]}.csv"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  if (type === 'pdf') {
    // PDF generation would use a library like pdf-lib in production
    // For now return a structured text report
    const report = `CarbonX Machine Health Report
Generated: ${new Date().toISOString()}
Gateway: RX-PLANT-01 (Main Plant Gateway)

SUMMARY
-------
Total Energy (24h): 2,450 kWh
Total CO₂: ${kwhToCo2Kg(2450)} kg
Avg Health Score: 70/100
Energy Loss: 5.3% (Acceptable)

TX NODE STATUS
--------------
TX-1 CNC Machine A    | Health: 95% | 12.4 kW | HEALTHY
TX-2 Lathe B          | Health: 88% | 8.2 kW  | HEALTHY  
TX-3 Compressor Array | Health: 62% | 45.1 kW | WARNING
TX-4 HVAC System      | Health: 35% | 64.8 kW | CRITICAL

RECOMMENDATIONS
---------------
• TX-4 HVAC: Schedule immediate inspection. Health score below 40%.
• TX-3 Compressor: Monitor closely. High operating temperature (88°C).
• Power factor improvement recommended for TX-3 and TX-4.

Report generated by CarbonX AI Industrial IoT Platform.
`;
    return new NextResponse(report, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="CarbonX_Machine_Report_${new Date().toISOString().split('T')[0]}.txt"`,
        'Cache-Control': 'no-store',
      },
    });
  }

  return NextResponse.json({ error: 'Invalid export type. Use ?type=csv or ?type=pdf' }, { status: 400 });
}
